### ISSUE TITLE
Question about the code

### ISSUE THREAD

**Issue by KongJiawei1231** [TreeLLi/APT#3]
The image batch should be normalized before it is fed into the CLIP model. The built-in data manager of Dassl has normalized the image, but it seems that the image is normalized again in CustormCLIP.
![image](https://github.com/user-attachments/assets/6998886a-5ec3-43b9-b63a-80731c023c86)

**Comment by TreeLLi** [comment]
Hi,

thanks for your interest in our work. The normalization function of Dassl is enabled through setting "normalize" transformation in the configuration file in the directory `/apt/configs/trainers/APT`. We deliberately disabled this by removing "normalize" from the transformation list `INPUT: TRANSFORMS: ` so that we can normalize the input in the same way as done in the RobustBench. For comparison, you can see that in the configuration file `rn101.yaml` “normalize” is still in the list which however is not used by us. Please let me know if you still have concerns.

**Comment by KongJiawei1231** [comment]
> Hi,
> 
> thanks for your interest in our work. The normalization function of Dassl is enabled through setting "normalize" transformation in the configuration file in the directory `/apt/configs/trainers/APT`. We deliberately disabled this by removing "normalize" from the transformation list `INPUT: TRANSFORMS: ` so that we can normalize the input in the same way as done in the RobustBench. For comparison, you can see that in the configuration file `rn101.yaml` “normalize” is still in the list which however is not used by us. Please let me know if you still have concerns.

Thanks very much for your answer!

**Comment by KongJiawei1231** [comment]
Thanks very much for your answer!
